config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  Rails.application.routes.draw do resources :books
    get '/books/search_similar_books/:id', to: 'books#search_similar_books', as: 'search_similar_books'
    root :to => redirect('/books')
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ActiveRecord::Base
    def self.all_genre ; ['Science fiction','Drama','Action and Adventure','Romance','Mystery','Horror'] ; end #  shortcut: array of strings
    validates :title, :presence => true
    #validates :publish_date, :presence => true
    validates :genre, :inclusion => {:in => Book.all_genre}
    #validate :all_number_isbn
    
    #def all_number_isbn
        #errors.add(:isbn_number, 'must be all numbers') if
          #isbn && !is_number?(isbn_number)
    #end
    
    #def is_number? string
        #true if Float(string) rescue false
    #end

    def self.similar_books(book)
        Book.where(author: book.author)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    sort = params[:sort] || session[:sort]
    case sort
    when 'title'
      ordering,@title_header = {:title => :asc}, 'hilite'
    when 'publish_date'      
      ordering,@date_header = {:publish_date => :asc}, 'hilite'
    end
    
    @all_genre = Book.all_genre
    
    if params[:genres]
      @selected_genres = params[:genres].permit!
    elsif session[:genres]
      @selected_genres = session[:genres]
    else
      @selected_genres = {}  
    end
    
    if @selected_genres == {}
      @selected_genres = Hash[@all_genre.map {|genre| [genre, genre]}]
    end
    
    if params[:sort] != session[:sort] or params[:genres] != session[:genres]
      session[:sort] = sort
      session[:genres] = @selected_genres
      redirect_to :sort => sort, :genres => @selected_genres and return
    end
 
    @books = Book.where(genre: @selected_genres.keys).order(ordering)
    
  end
  
  def search_similar_books
    @book = Book.find(params[:id])
    if @book.author.to_s.empty?
      flash[:warning] = "'#{@book.title}' has no author info"
      redirect_to books_path
    else
      @books = Book.similar_books(@book)
    end
  end

  def show
    id = params[:id]
    @book = Book.find(id)
  end

  def new
    @book = Book.new
    # default: render 'new' template
  end
  
  def create
    params.require(:book)
    permitted = params[:book].permit(:title,:genre,:description,:isbn_number,:author,:publish_date)
    @book = Book.create!(permitted)
    if @book.save
      flash[:success] = "#{@book.title} was successfully created."
      redirect_to books_path
    else
      render 'new'
    end
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find params[:id]
    params.require(:book)
    permitted = params[:book].permit(:title,:genre,:description, :isbn_number,:author,:publish_date)
    @book.update_attributes!(permitted)
    if @book.update_attributes(permitted)
      flash[:success] = "#{@book.title} was successfully updated."
      redirect_to books_path(@book)
    else
      render 'edit'
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:success] = "Book '#{@book.title}' deleted."
    redirect_to books_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.haml
%h2 Edit Book
 
= form_tag book_path(@book), :method => :put do

  = label :book, :title, 'Title'
  = text_field :book, 'title'
  
  = label :book, :author, 'Author'
  = text_field :book, 'author'
  
  = label :book, :isbn_number, 'ISBN'
  = text_field :book, :isbn_number
 
  = label :book, :genre, 'Genre'
  = select :book, :genre, ['Science fiction','Drama','Action and Adventure','Romance','Mystery','Horror']
 
  = label :book, :publish_date, 'Published On'
  = date_select :book, :publish_date
  
  = label :book, :description, 'Description'
  = text_field :book, 'description'
  
  = submit_tag 'Update Book Info'

app/views/books/index.html.haml
%h1 All Books
= form_tag books_path, :method => :get, :id => 'ratings_form' do
  = hidden_field_tag ":title_sort", true if @title_header
  = hidden_field_tag ":publish_date_sort", true if @date_header
  Include:
  - @all_genre.each do |genre|
    = genre
    = check_box_tag "genres[#{genre}]", 1, @selected_genres.include?(genre), :id => "genres_#{genre}"
  = submit_tag 'Refresh'

%table#books
  %thead
    %tr
      %th{:class => @title_header}= link_to 'Book Title', books_path(:sort => 'title', :ratings => @selected_ratings), :id => 'title_header'
      %th Genre
      %th ISBN Number
      %th{:class => @date_header}= link_to 'Publish Date', books_path(:sort => 'publish_date', :ratings => @selected_ratings), :id => 'publish_date_header'
      %th More Info
  %tbody
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.genre
        %td= book.isbn_number
        %td= book.publish_date
        %td= link_to "More about book", book_path(book)
        
= link_to 'Add new book', new_book_path

app/views/books/new.html.haml
%h2 Create New Book
 
= form_tag books_path, :method => :post do

  - unless @book.errors.empty?
    #warning
      Errors prevented this book from being #{controller.action_name}d:
      %ul
        - @book.errors.full_messages.each do |error|
          %li= error
 
  = label :book, :title, 'Title'
  = text_field :book, :title
  
  = label :book, :author, 'Author'
  = text_field :book, 'author'
 
  = label :book, :genre, 'Genre'
  = select :book, :genre, ['Science fiction','Drama','Action and Adventure','Romance','Mystery','Horror']
 
  = label :book, :isbn_number, 'ISBN'
  = text_field :book, :isbn_number
  
  = label :book, :publish_date, 'Publish On'
  = date_select :book, :publish_date
  
  = label :book, :description, 'Description'
  = text_field :book, 'description'
 
  = submit_tag 'Save Changes'

app/views/books/search_similar_books.html.haml
%h1 Books by "#{@book.author}"

%table#books
  %thead
    %tr
      %th Movie Title
      %th Genre
      %th ISBN Number
      %th Publish Date
      %th More Info
  %tbody
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.genre
        %td= book.isbn_number
        %td= book.publish_date
        %td= link_to "More info", book_path(book)
        
= link_to 'Back To Info', book_path(@book)
= link_to 'Back to all books list', books_path

app/views/books/show.html.haml
%h2 Details about #{@book.title}
 
%ul#details
  %li
    Author:
    = @book.author
  %li
    Genre:
    = @book.genre
  %li
    Isbn:
    = @book.isbn_number
  %li
    Publish Date:
    = @book.publish_date.strftime("%B %d, %Y")
 
%h3 Description:
 
%p#description= @book.description

= link_to 'Back to books list', books_path
= link_to 'Edit info', edit_book_path(@book)
= link_to 'Delete', book_path(@book), :method => :delete
= link_to 'Find Books With Same Author', search_similar_books_path(@book)

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title MyFavouriteBooks!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
 
  %body
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    #main
      = yield